# This workflow will run when there's a push event on master branch
name: Deploy to remote server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}  # the IP or domain of your remote server
        username: ${{ secrets.REMOTE_USER }}  # the username of your remote server
        key: ${{ secrets.REMOTE_SSH_KEY }}  # the private SSH key of your remote server
        script: |  # commands to be executed on the remote server
          cd /var/www/html/bebras-platform/teacherInterface/bebras-tasks/_common/modules
          git checkout master
          git fetch origin
          git reset --hard origin/master
          git pull origin master
